### ISSUE TITLE
Win 7 EmptyDevice List

### ISSUE THREAD

**Issue by DPSB** [smartxworks/pySMART#9]
Hello! 
I'm trying to get pysmart to work, I want to use it on Windows PE with python 3.4.4 in our testing environment. But before testing on WinPE i want to try it out on Windows 7.
I have used the 0.3.6 from github and added the changes (same you have added for 0.3.7 now)

I also had to add   
` from functools import wrap`
to line 124 (before the @wraps) in utils.py

In the device_list.py i had to change line 98 because of "str does not support buffer interface" error, 
so i've added 
`_stdout.decode("utf-8").split('\n')`
 to this line. 

So far its now starting without any errors...but:
The rescan_device_busses function always opens a diskpart window, without closing it automatically and pySMART.DeviceList() isn't returning anything. 
It only shows a empty line, even when diskpart 'list disk' command shows four disks.

Any suggestions? Should i try the 0.3.7? Or am i missing something?

**Comment by winkidney** [comment]
## What 0.3.7 done.
0.3.7 may not have been solved this problem.
It just solved the python3's default stdout's data-type(from bytes to string.)

## Why diskpart window appears
Please check your smartctl tools pakcage, I think the problem is that your version of smartctl-tools command-line option is not the same as it on linux(or our version)

FYI, my output of "smartctl --version" is 
```
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.4.0-93-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

smartctl comes with ABSOLUTELY NO WARRANTY. This is free
software, and you are welcome to redistribute it under
the terms of the GNU General Public License; either
version 2, or (at your option) any later version.
See http://www.gnu.org for further details.

smartmontools release 6.5 dated 2015-06-04 at 16:29:41 UTC
smartmontools SVN rev 4214 dated 2016-01-24 at 22:53:37
smartmontools build host: x86_64-pc-linux-gnu
smartmontools build with: GCC 5.3.1 20160205
smartmontools configure arguments:  '--prefix=/usr' '--build=x86_64-linux-gnu' '--host=x86_64-linux-gnu' '--sysconfdir=/etc' '--mandir=/usr/share/man' '--with-initscriptdir=no' '--docdir=/usr/share/doc/smartmontools' '--with-savestates=/var/lib/smartmontools/smartd.' '--with-attributelog=/var/lib/smartmontools/attrlog.' '--with-exampledir=/usr/share/doc/smartmontools/examples/' '--with-drivedbdir=/var/lib/smartmontools/drivedb' '--with-systemdsystemunitdir=/lib/systemd/system' '--with-smartdscriptdir=/usr/share/smartmontools' '--with-smartdplugindir=/etc/smartmontools/smartd_warning.d' '--with-systemdenvfile=/etc/default/smartmontools' '--with-selinux' 'build_alias=x86_64-linux-gnu' 'host_alias=x86_64-linux-gnu' 'CXXFLAGS=-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -fsigned-char -Wall -O2' 'LDFLAGS=-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -fsigned-char -Wall -O2'
```

**Comment by DPSB** [comment]
As far as i can see is the diskpart window opend during the rescan_device_busses function inside the utils.py, where an echo "rescan" is piped to diskpart.  This will always remain diskpart open, as long as there is no exit command typed to diskpart.

Better way to call diskpart would be to create a diskpart skript file (txt) which contains the rescan and exit commands(2 lines). Then you could call it in python with echo "diskpart /s pathtoSkripFile" | cmd /c 
This will make sure cmd window is terminated after commands execution.

The output of smartctl --version is
```
 smartctl 6.5 2016-05-07 r4318 [x86_64-w64-mingw32-win7-sp1] (sf-6.5-1)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org
smartctl comes with ABSOLUTELY NO WARRANTY. This is free
software, and you are welcome to redistribute it under
the terms of the GNU General Public License; either
version 2, or (at your option) any later version.
See http://www.gnu.org for further details.
smartmontools release 6.5 dated 2016-05-07 at 11:17:46 UTC
smartmontools SVN rev 4318 dated 2016-05-07 at 11:18:20
smartmontools build host: x86_64-w64-mingw32
smartmontools build with: C++98, GCC 4.9.1
smartmontools configure arguments: 'build_alias=i686-pc-linux-gnu' 'host_alias=x
86_64-w64-mingw32' 'LDFLAGS=-static'
```

So yes, im using a newer version of smartctl, but the cli syntax is still the same.
When typing "smartctl --scan-open" manually into cmd i get the following output 

```
/dev/sda -d ata # /dev/sda, ATA device
/dev/sdb -d ata # /dev/sdb, ATA device
/dev/sdc -d ata # /dev/sdc, ATA device
# /dev/sdd -d scsi # /dev/sdd, SCSI device open failed: \\.\PhysicalDrive3: Open
 failed, Error=5
```

I'll try with your version, but i think it's more like a windows problem, then a version problem.

**Comment by DPSB** [comment]
Okay, so i've now removed the path from line 95 in device_list.py
 ```
       cmd = Popen('smartctl --scan-open', shell=True,
                    stdout=PIPE, stderr=PIPE)
```
i get now following output
```
Traceback (most recent call last):
  File "W:/SIE/SMARTLOG/trunk/src/SMARTLOG.py", line 2, in <module>
    devicelist = pySMART.DeviceList()
  File "C:\Tools\Python\Python_3.4.4-x64\lib\site-packages\pySMART\device_list.py", line 52, in __init__
    self._initialize()
  File "C:\Tools\Python\Python_3.4.4-x64\lib\site-packages\pySMART\device_list.py", line 116, in _initialize
    self.devices.append(Device(name, interface=interface))
  File "C:\Tools\Python\Python_3.4.4-x64\lib\site-packages\pySMART\device.py", line 143, in __init__
    "This object should be destroyed.".format(name))
NameError: name 'name' is not defined
```
with the default line which contains the path to linux version, i get no output at all.
`cmd = Popen('/usr/bin/env smartctl --scan-open', shell=True,`

Do i have to adapt pysmart per default to get it working on windows? Or do i have to install the cygwin version of smartctl on windows? (using the 'native' version atm)

**Comment by winkidney** [comment]
Installition for cygwin version is not necessary.

You could import `platform` module to detect if this platform is windows and then, decide whether to use `/usr/bin/env` to run such a command.

**Comment by DPSB** [comment]
OS detection is done in the line 93 from device_list.py
So it has some windows specific lines, but i still have to change the path? Anyway, even with manually adding the path it returns nothing. But maybe that's related to the .decode(utf-8) change i've added to devices_list.py in line 98..(?)(Sorry, i'm still a python noob)

BTW with version 0.3.7 i still get the 
`TypeError 'str' does not support the buffer interface` when running DeviceList() on python 3.4.4-x64 

To fix this error i've changed line 98 to
` for line in _stdout.decode('utf-8').split('\n'):`

**Comment by DPSB** [comment]
Alright, so now i've got some output, after i hardcoded the path, (relative path did not worked)

First i've  got some name not defined error, because of missing "self" in device.py in line 131 & 143

 ```
       if self.name is None:
            warnings.warn("\nDevice '{0}' does not exist! "
                          "This object should be destroyed.".format(**self**.name))
            return
        # If no interface type was provided, scan for the device
        elif self.interface is None:
            _grep = 'find' if OS == 'Windows' else 'grep'
            _stdout, _stderr = self._cmd_scan_open(_grep)
            if _stdout != '':
                self.interface = _stdout.split(' ')[2]
                # Disambiguate the generic interface to a specific type
                self._classify()
            else:
                warnings.warn("\nDevice '{0}' does not exist! "
                              "This object should be destroyed.".format(**self.**name))
```

After changing that, i now get the following output when running `devicelist = pySMART.DeviceList()`:

```
C:\Tools\Python\Python_3.4.4-x64\lib\site-packages\pySMART\device.py:143: UserWarning: 
Device 'sda' does not exist! This object should be destroyed.
C:\Tools\Python\Python_3.4.4-x64\lib\site-packages\pySMART\device.py:143: UserWarning: 
Device 'sdb' does not exist! This object should be destroyed.
C:\Tools\Python\Python_3.4.4-x64\lib\site-packages\pySMART\device.py:143: UserWarning: 
Device 'sdc' does not exist! This object should be destroyed.
C:\Tools\Python\Python_3.4.4-x64\lib\site-packages\pySMART\device.py:143: UserWarning: 
Device 'sdd' does not exist! This object should be destroyed.
```

Any ideas? When i open smartctl via windows cmd i can see the four sd* devices,..is this some windows/linux compatibility problem?

**Comment by DPSB** [comment]
Alright, found the reason why it fails, We have to remove the paths to smartctl inside the device_list.py and device.py functions. Then it will work on windows too, as long as smartctl folder is in windows path.

There are already some functions written like that, e.g. 
_cmd_get_capabilities 
but others have the "usr/bin/env" path. 
This will cause some windows "The system cannnot find the path specified" errors.

**Comment by DPSB** [comment]
with version 0.3.7 you'll need to make the following changes to get it running on windows 7 and python 3.4.4:
```
  File "C:\Tools\Python\Python_3.4.4-x64\lib\site-packages\pySMART\device_list.py", line 98, in _initialize
    for line in _stdout.split('\n'):
TypeError: 'str' does not support the buffer interface
```
Fix this by changing line 98 in device_list,py
`for line in _stdout.decode('utf-8').split('\n'):`
After that, you'll see an empty devicelist when running 
```
devicelist = pySMART.DeviceList()
print(devicelist)
```
Change line 95 in device_list.py 
`        cmd = Popen('/usr/bin/env smartctl --scan-open', shell=True,`
to
      `  cmd = Popen('smartctl --scan-open', shell=True,`

Next open the device.py

add the two selfs to lines 131 and 143 
`"This object should be destroyed.".format(name))`
to
`"This object should be destroyed.".format(self.name))`

remove the path in line 418, 426, 505

**Comment by winkidney** [comment]
## EncodeError
`for line in _stdout.decode('utf-8').split('\n')`

Has been resolved in 0.3.7

## Binary-path error

Not resolved, you have to solve it by yourself.

## Other

Would you like to make a pull request ?

**Comment by DPSB** [comment]
The encode error still exists in 0.3.7

I've created a branch("pysmart_windows_fixed") from "master"-branch and fixed the binary paths and the encode error, can you give me the rights to upload it? ATM i'm not allowed to upload a new branch, which is requiered for pull requests(?)

**Comment by winkidney** [comment]
You could just fork and upload it to your own repo.
Then push it to your branch just like the following
```
git remote add upstream <url-to-your-own-repo> 
git push upstream <branch-name>
```
And now, you can create a pull request on github's website.

**Comment by DPSB** [comment]
thx, done.

**Comment by winkidney** [comment]
closed
